### ISSUE TITLE
tf.lite file issue

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/Flood-Model#10]

**Comment by BentleySettin** [comment]
Quick question; I reset the openMV cam because it was doing some off things that I have not seen. We finally got the Boron working as it was having a major DeviceOS issue. Now that I have reset the camera, I am uploading the main.py and trying to put the tf.lite file back into the OpenMV hard drive. It keeps saying this file is too big even though I have done this before and never got this issue. I tried zipping it too. 

Any recommendations? 

There is an SD card and I tried copying/pasting

**Comment by BentleySettin** [comment]
@ebgoldstein Looks like its the openmv. Used a different computer, same issue. Tried the other openMV and it read the full SD .

**Comment by ebgoldstein** [comment]
there we go... can you use the other openmv board?

**Comment by BentleySettin** [comment]
@ebgoldstein yes I am! I am still experiencing green flashing when I plug it in. Based on some forums it is the [bootloader running](https://forums.openmv.io/t/green-led-keeps-blinking/2000/6). This may be normal but all last semester I did not see this occur. 

I am looking more into this to make sure my next step does not cause any issues. I am wondering if you have experienced this at all? 

More help:
https://forums.openmv.io/t/flashing-green-then-white-once-then-dead-bricked/1575

**Comment by ebgoldstein** [comment]
I don't remember right now- I guess the real test is if the code is successfully running (with the tflite file )

**Comment by BentleySettin** [comment]
@ebgoldstein After the code runs I have a LED red turn on and off which is successfully occuring **once**. 

I understand that while the camera is connected to the IDE the camera waits for you to press run which means it will only run once, however, it is only running once when connected/powered by the Boron which is new. 

I have tried to power it from USB to the wall but still nothing. 

UPDATE: I changed the LED to 2 red flashes just to make sure it was actually telling me it was running through the code and it was not just a red flash. However, I only got one flash after it tries to run the code which means it may NOT be making it through the code.

**Comment by ebgoldstein** [comment]
I am going to test this on my device & machine...

**Comment by ebgoldstein** [comment]
@BentleySettin , see the new openmv code i just committted.. this one worked on my device.. the old version did not.. Can you please try it and LMK?

(@anardek & @SUPScientist - maybe ignore my email, this version of the code seems to work on my machine and I was able to reproduce the issues that @BentleySettin was having... this code shoudl work :crossed_fingers: )

**Comment by BentleySettin** [comment]
@ebgoldstein it works! Thank you Evan!
