### ISSUE TITLE
OpenMV power supply issues.

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/Flood-Model#11]
The OpenMV is displaying a variety of LEDs when connected to a variety of power sources. When the Boron and OpenMV are connected to solar panel and battery there is an indefinite white light. When the Boron and OpenMV are connected USB via my computer and battery there is a flashing white light. When both devices are connected to USB there are no LED's besides an occasional green flashing that lasts for a few seconds.

**Comment by BentleySettin** [comment]
@SUPScientist  According to the battery charge numbers on visual studio the battery is at a 4.11 charge. I am determining VUSB voltage too

**Comment by BentleySettin** [comment]
@SUPScientist how do I determine voltage from battery?

**Comment by SUPScientist** [comment]
Please edit initial post in this issue to describe symptoms you're seeing, suspected causes, and your work plan to evaluate potential solutions.

**Comment by SUPScientist** [comment]
> @SUPScientist how do I determine voltage from battery?  

Too vague. Which battery? LiPo plugged into the JST connector on the Boron? Battery pack attached to the solar panel? If LiPo on the JST connector on the Boron, you can use the firmware to spit out the voltage. For either battery, you can use the multimeter in voltage mode measuring across the positive and negative leads on the battery's cable.

**Comment by SUPScientist** [comment]
Also, how did this issue end up in this repo? Aren't you only actively maintaining https://github.com/TinyCamML/Boron-and-OpenMV at this point?

**Comment by BentleySettin** [comment]
@SUPScientist  I edited the caption. I placed in this because I thought of it more as an openMV issue based on it being the only device that is experiencing difficulty but I understand I should place this in Boron-and-OpenMV. 

Apologies, I meant for my previous comment to be a response to your "Next steps" where you said to check the solar panel battery. Thank you.

**Comment by SUPScientist** [comment]
Roger that. I know it gets confusing with the various repos. Since the issue pertains quite specifically to the current iteration of the project wherein the Boron and OpenMV are connected, transmitting data via UART, transmitting data via cellular, and sleeping, I think this belongs in a different repository. I will close this issue here and reopen in https://github.com/TinyCamML/Boron-and-OpenMV/issues/7.
