### ISSUE TITLE
Run OpenMV code from Evan

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/Flood-Model#3]

**Comment by BentleySettin** [comment]
When I ran the openMV code it says that there is an OSerror and it cannot find the file. Based on research I need to plug the camera in and when it pulls up the SD file already stored in the camera I can add the .tflite file it is looking for. I then reset the camera and run the script. 

https://forums.openmv.io/t/could-not-find-file/6523/13 <--- Helpful site

**Comment by BentleySettin** [comment]
I have successfully uploaded the .tflite file onto the OpenMV but it is still saying the file is not found. I also reset the camera after uploading the .tflite file and main.py file onto the SD card and it is still saying no file is found. 

Some research has said sometimes the file is too big (greater than 4 mg), but this file is only 3.88 mg.

**Comment by ebgoldstein** [comment]
based on discussion in https://github.com/TinyCamML/Boron/issues/8#issuecomment-1767019585 , i think we can close this issue
