### ISSUE TITLE
Wake openMV at predetermined time intervals

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/Flood-Model#8]

**Comment by BentleySettin** [comment]
https://docs.openmv.io/library/pyb.html       <--- py.stop
https://docs.openmv.io/library/pyb.RTC.html     <--- rtc.wakeup

Information on py.stop and then rtc.wakeup. Seems to be most recommended way to put the camera in low power mode and wake up from an external RTC wakeup which can come from the Boron.

After testing the added code:
rtc = py.RTC()
sensor.sleep(True)
rtc.wakeup(30000) <--- 30 seconds

I keep getting the area message "Run time error: Frame Capture has timed out". I did some research and the creators said that "Frame capture timeout is generated by the camera frame grabber process not getting a frame after 3000ms ... This happens because something related to the camera sensor crashed."

**Comment by BentleySettin** [comment]
@ebgoldstein Have you dealt with a camera sensor crash? Or how to get it to not crash. ^^

**Comment by BentleySettin** [comment]
I tried pyb.stop and it seems to start up, prints "Flood" once, and then stops as it should. After it stops I recieve a message from my computer saying...

"USB device not recongized: The last USB device you connected to this computer malfunctioned, and Windows does not recognize it."

I am now using :

sensor.sleep()
time.sleep(10) 

This works. I am trying to find how much energy sensor.sleep would actually save compared to pyb.stop. I also don't know how realistic this method will be because if timing for Boron to wake up and be ready to recieve data is not lined up with openMV being awake then it will capture no data.

**Comment by BentleySettin** [comment]
OpenMV is successfully waking up on time intervals controlled by the Boron. The line I am attaching is the code function "callback" that occurs when the Boron sends a message, which is every minute. 

https://github.com/TinyCamML/OMVmodel/blob/aeeb494a62d77ec100895ad152d8dadbaa6e63a1/updatedOpenMVCode.py#L40

**Comment by ebgoldstein** [comment]
great work @BentleySettin !
